[object_store]
bucket_base_url = "base_url"
mode = "FileBacked"
file_backed_base_path = "artifacts"
credential_file_path = "/path/to/credentials.json"
max_retries = 5

[public_object_store]
bucket_base_url = "public_base_url"
mode = "FileBacked"
file_backed_base_path = "artifacts_public"
credential_file_path = "/path/to/credentials.json"
max_retries = 5

[prover_object_store]
bucket_base_url = "prover_base_url"
mode = "FileBacked"
file_backed_base_path = "artifacts_prover"
credential_file_path = "/path/to/credentials.json"
max_retries = 5

[snapshots_object_store]
bucket_base_url="snapshots_base_url"
mode="FileBacked"
file_backed_base_path="artifacts_snapshots"
credential_file_path="/path/to/credentials.json"
max_retries=5
